print(serpent.block(registry))
print("ezatarf")
print(event)
-- print(event.__index)
-- print(bot.__index)
-- print(map.__index)
print(getmetatable(event))
print(getmetatable(bot))
print(getmetatable(map))